import {
  Injectable,
  NotFoundException,
  ConflictException,
  Logger,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../../common/prisma/prisma.service.js';
import { SettingsService } from '../settings/settings.service.js';
import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';

const LABELS = {
  id: {
    invoice: 'FAKTUR',
    invoiceNumber: 'No. Faktur',
    date: 'Tanggal',
    billTo: 'Tagihan Untuk',
    student: 'Siswa',
    class: 'Kelas',
    parent: 'Orang Tua',
    description: 'Deskripsi',
    amount: 'Jumlah',
    total: 'Total',
    dueDate: 'Jatuh Tempo',
    status: 'Status',
    statusPending: 'Belum Lunas',
    statusPaid: 'Lunas',
    statusOverdue: 'Terlambat',
    paymentInstructions: 'Instruksi Pembayaran',
    footer: 'Dibuat oleh Sinaloka Platform',
  },
  en: {
    invoice: 'INVOICE',
    invoiceNumber: 'Invoice No.',
    date: 'Date',
    billTo: 'Bill To',
    student: 'Student',
    class: 'Class',
    parent: 'Parent',
    description: 'Description',
    amount: 'Amount',
    total: 'Total',
    dueDate: 'Due Date',
    status: 'Status',
    statusPending: 'Pending',
    statusPaid: 'Paid',
    statusOverdue: 'Overdue',
    paymentInstructions: 'Payment Instructions',
    footer: 'Generated by Sinaloka Platform',
  },
};

@Injectable()
export class InvoiceService {
  private readonly logger = new Logger(InvoiceService.name);
  private readonly uploadDir: string;

  constructor(
    private readonly prisma: PrismaService,
    private readonly settingsService: SettingsService,
    private readonly configService: ConfigService,
  ) {
    this.uploadDir = this.configService.get('UPLOAD_DIR', './uploads')!;
  }

  async generateInvoice(institutionId: string, paymentId: string) {
    const payment = await this.prisma.payment.findFirst({
      where: { id: paymentId, institution_id: institutionId },
      include: {
        student: true,
        enrollment: { include: { class: true } },
      },
    });

    if (!payment) {
      throw new NotFoundException('Payment not found');
    }

    if (payment.invoice_number) {
      throw new ConflictException('Invoice already exists for this payment');
    }

    const institution = await this.prisma.institution.findUnique({
      where: { id: institutionId },
    });

    if (!institution) {
      throw new NotFoundException('Institution not found');
    }

    const billing = await this.settingsService.getBilling(institutionId);
    const lang = (institution.default_language === 'en' ? 'en' : 'id') as keyof typeof LABELS;
    const l = LABELS[lang];

    const invoiceNumber = await this.generateInvoiceNumber(institutionId);

    const pdfBuffer = await this.generatePdf({
      institution,
      payment,
      invoiceNumber,
      bankAccounts: billing.bank_accounts ?? [],
      labels: l,
      lang,
    });

    const invoiceDir = path.join(this.uploadDir, institutionId, 'invoices');
    fs.mkdirSync(invoiceDir, { recursive: true });

    const filename = `${invoiceNumber.replace(/\//g, '-')}.pdf`;
    const filepath = path.join(invoiceDir, filename);
    fs.writeFileSync(filepath, pdfBuffer);

    const invoiceUrl = `${institutionId}/invoices/${filename}`;

    const updated = await this.prisma.payment.update({
      where: { id: paymentId },
      data: { invoice_number: invoiceNumber, invoice_url: invoiceUrl },
      include: {
        student: true,
        enrollment: { include: { class: true } },
      },
    });

    this.logger.log(`Invoice ${invoiceNumber} generated for payment ${paymentId}`);
    return updated;
  }

  private async generateInvoiceNumber(institutionId: string): Promise<string> {
    // Use a transaction with serializable isolation to prevent race conditions
    return this.prisma.$transaction(async (tx) => {
      const institution = await tx.institution.findUnique({
        where: { id: institutionId },
        select: { settings: true },
      });

      const settings = (institution?.settings as any) ?? {};
      const billing = settings.billing ?? {};
      const prefix = billing.invoice_prefix ?? 'INV-';
      const counter = billing.invoice_counter ?? {};

      const now = new Date();
      const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
      const yyyymm = monthKey.replace('-', '');

      const currentCount = (counter[monthKey] ?? 0) + 1;
      counter[monthKey] = currentCount;

      await tx.institution.update({
        where: { id: institutionId },
        data: {
          settings: {
            ...settings,
            billing: { ...billing, invoice_counter: counter },
          },
        },
      });

      return `${prefix}${yyyymm}-${String(currentCount).padStart(3, '0')}`;
    }, { isolationLevel: 'Serializable' });
  }

  private async generatePdf(params: {
    institution: any;
    payment: any;
    invoiceNumber: string;
    bankAccounts: any[];
    labels: (typeof LABELS)['id'];
    lang: string;
  }): Promise<Buffer> {
    const { institution, payment, invoiceNumber, bankAccounts, labels } = params;
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));

    const locale = params.lang === 'id' ? 'id-ID' : 'en-US';
    const formatAmount = (amount: number) =>
      new Intl.NumberFormat(locale, {
        style: 'currency',
        currency: 'IDR',
        minimumFractionDigits: 0,
      }).format(amount);

    const formatDate = (date: Date | string) =>
      new Date(date).toLocaleDateString(locale, {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      });

    // --- Header ---
    let headerY = 50;
    if (institution.logo_url) {
      try {
        const logoPath = path.resolve(this.uploadDir, institution.logo_url);
        // Prevent path traversal: ensure resolved path stays within uploadDir
        const resolvedUploadDir = path.resolve(this.uploadDir);
        if (
          logoPath.startsWith(resolvedUploadDir + path.sep) &&
          fs.existsSync(logoPath)
        ) {
          doc.image(logoPath, 50, headerY, { width: 50 });
        }
      } catch {
        // Skip logo on error
      }
    }

    const textX = institution.logo_url ? 110 : 50;
    doc.fontSize(16).font('Helvetica-Bold').text(institution.name, textX, headerY);
    doc.fontSize(9).font('Helvetica');
    if (institution.address) doc.text(institution.address, textX);
    const contactParts = [institution.phone, institution.email].filter(Boolean);
    if (contactParts.length) doc.text(contactParts.join(' | '), textX);

    doc.moveDown(2);

    // Separator
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e4e4e7');
    doc.moveDown();

    // --- Invoice title ---
    doc.fontSize(20).font('Helvetica-Bold').text(labels.invoice, { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica');
    doc.text(`${labels.invoiceNumber}: ${invoiceNumber}`, { align: 'center' });
    doc.text(`${labels.date}: ${formatDate(new Date())}`, { align: 'center' });
    doc.moveDown();

    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e4e4e7');
    doc.moveDown();

    // --- Bill To ---
    doc.fontSize(11).font('Helvetica-Bold').text(labels.billTo);
    doc.fontSize(10).font('Helvetica');
    doc.text(`${labels.student}: ${payment.student?.name ?? '-'}`);
    if (payment.enrollment?.class) {
      doc.text(`${labels.class}: ${payment.enrollment.class.name}`);
    }
    if (payment.student?.parent_name) {
      doc.text(`${labels.parent}: ${payment.student.parent_name}`);
    }
    doc.moveDown();

    // --- Amount table ---
    const tableY = doc.y;
    doc.font('Helvetica-Bold').fontSize(10);
    doc.text(labels.description, 50, tableY);
    doc.text(labels.amount, 400, tableY, { align: 'right', width: 145 });

    doc.moveTo(50, tableY + 18).lineTo(545, tableY + 18).stroke('#e4e4e7');

    doc.font('Helvetica').fontSize(10);
    const itemY = tableY + 26;
    const className = payment.enrollment?.class?.name ?? 'Payment';
    doc.text(className, 50, itemY);
    doc.text(formatAmount(Number(payment.amount)), 400, itemY, { align: 'right', width: 145 });

    doc.moveDown(3);

    // Total
    doc.font('Helvetica-Bold');
    doc.text(labels.total, 300, doc.y);
    doc.text(formatAmount(Number(payment.amount)), 400, doc.y - doc.currentLineHeight(), { align: 'right', width: 145 });
    doc.font('Helvetica');
    doc.moveDown();

    // Due date + status
    const statusMap: Record<string, string> = {
      PENDING: labels.statusPending,
      PAID: labels.statusPaid,
      OVERDUE: labels.statusOverdue,
    };
    doc.text(`${labels.dueDate}: ${formatDate(payment.due_date)}`);
    doc.text(`${labels.status}: ${statusMap[payment.status] ?? payment.status}`);
    doc.moveDown();

    // --- Bank accounts ---
    if (bankAccounts.length > 0) {
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e4e4e7');
      doc.moveDown();

      doc.font('Helvetica-Bold').fontSize(11).text(labels.paymentInstructions);
      doc.font('Helvetica').fontSize(10);
      doc.moveDown(0.5);

      for (const acc of bankAccounts) {
        doc.text(`${acc.bank_name} — ${acc.account_number} a/n ${acc.account_holder}`);
      }
      doc.moveDown();
    }

    // --- Footer ---
    doc.moveTo(50, doc.y + 10).lineTo(545, doc.y + 10).stroke('#e4e4e7');
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#a1a1aa').text(labels.footer, { align: 'center' });

    doc.end();
    return new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));
  }
}
