import {
  Injectable,
  NotFoundException,
  ConflictException,
  Logger,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../../common/prisma/prisma.service.js';
import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';

const LABELS = {
  id: {
    payoutSlip: 'SLIP PEMBAYARAN',
    slipNumber: 'No. Slip',
    date: 'Tanggal',
    payTo: 'Dibayarkan Kepada',
    tutor: 'Pengajar',
    bankAccount: 'Rekening Bank',
    period: 'Periode',
    sessionBreakdown: 'Rincian Sesi',
    sessionDate: 'Tanggal',
    className: 'Kelas',
    fee: 'Biaya',
    total: 'Total',
    netPayout: 'Total Pembayaran Bersih',
    status: 'Status',
    statusPending: 'Belum Diproses',
    statusProcessing: 'Diproses',
    statusPaid: 'Lunas',
    footer: 'Dibuat oleh Sinaloka Platform',
  },
  en: {
    payoutSlip: 'PAYOUT SLIP',
    slipNumber: 'Slip No.',
    date: 'Date',
    payTo: 'Pay To',
    tutor: 'Tutor',
    bankAccount: 'Bank Account',
    period: 'Period',
    sessionBreakdown: 'Session Breakdown',
    sessionDate: 'Date',
    className: 'Class',
    fee: 'Fee',
    total: 'Total',
    netPayout: 'Net Payout',
    status: 'Status',
    statusPending: 'Pending',
    statusProcessing: 'Processing',
    statusPaid: 'Paid',
    footer: 'Generated by Sinaloka Platform',
  },
};

@Injectable()
export class PayoutSlipService {
  private readonly logger = new Logger(PayoutSlipService.name);
  private readonly uploadDir: string;

  constructor(
    private readonly prisma: PrismaService,
    private readonly configService: ConfigService,
  ) {
    this.uploadDir = this.configService.get('UPLOAD_DIR', './uploads')!;
  }

  async generateSlip(institutionId: string, payoutId: string) {
    const payout = await this.prisma.payout.findFirst({
      where: { id: payoutId, institution_id: institutionId },
      include: {
        tutor: {
          include: { user: { select: { name: true } } },
        },
      },
    });

    if (!payout) {
      throw new NotFoundException('Payout not found');
    }

    if (payout.slip_url) {
      throw new ConflictException('Payout slip already generated');
    }

    const institution = await this.prisma.institution.findUnique({
      where: { id: institutionId },
    });

    if (!institution) {
      throw new NotFoundException('Institution not found');
    }

    const lang = (institution.default_language === 'en' ? 'en' : 'id') as keyof typeof LABELS;
    const l = LABELS[lang];

    const slipNumber = await this.generateSlipNumber(institutionId);

    // Fetch sessions for the payout period
    const sessions =
      payout.period_start && payout.period_end
        ? await this.prisma.session.findMany({
            where: {
              institution_id: institutionId,
              class: { tutor_id: payout.tutor_id },
              status: 'COMPLETED',
              tutor_fee_amount: { not: null },
              date: { gte: payout.period_start, lte: payout.period_end },
            },
            include: { class: { select: { name: true } } },
            orderBy: { date: 'asc' },
          })
        : [];

    const pdfBuffer = await this.generatePdf({
      institution,
      payout,
      sessions,
      slipNumber,
      labels: l,
      lang,
    });

    const slipDir = path.join(this.uploadDir, institutionId, 'slips');
    fs.mkdirSync(slipDir, { recursive: true });

    const filename = `${slipNumber.replace(/\//g, '-')}.pdf`;
    const filepath = path.join(slipDir, filename);
    fs.writeFileSync(filepath, pdfBuffer);

    const slipUrl = `${institutionId}/slips/${filename}`;

    const updated = await this.prisma.payout.update({
      where: { id: payoutId },
      data: { slip_url: slipUrl },
      include: {
        tutor: { include: { user: { select: { name: true } } } },
      },
    });

    this.logger.log(`Payout slip ${slipNumber} generated for payout ${payoutId}`);
    return this.flattenPayoutTutor(updated);
  }

  private async generateSlipNumber(institutionId: string): Promise<string> {
    return this.prisma.$transaction(async (tx) => {
      const institution = await tx.institution.findUnique({
        where: { id: institutionId },
        select: { settings: true },
      });

      const settings = (institution?.settings as any) ?? {};
      const billing = settings.billing ?? {};
      const counter = billing.payout_slip_counter ?? {};

      const now = new Date();
      const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
      const yyyymm = monthKey.replace('-', '');

      const currentCount = (counter[monthKey] ?? 0) + 1;
      counter[monthKey] = currentCount;

      await tx.institution.update({
        where: { id: institutionId },
        data: {
          settings: {
            ...settings,
            billing: { ...billing, payout_slip_counter: counter },
          },
        },
      });

      return `PAY-${yyyymm}-${String(currentCount).padStart(3, '0')}`;
    }, { isolationLevel: 'Serializable' });
  }

  private async generatePdf(params: {
    institution: any;
    payout: any;
    sessions: any[];
    slipNumber: string;
    labels: (typeof LABELS)['id'];
    lang: string;
  }): Promise<Buffer> {
    const { institution, payout, sessions, slipNumber, labels } = params;
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));

    const locale = params.lang === 'id' ? 'id-ID' : 'en-US';
    const formatAmount = (amount: number) =>
      new Intl.NumberFormat(locale, {
        style: 'currency',
        currency: 'IDR',
        minimumFractionDigits: 0,
      }).format(amount);

    const formatDate = (date: Date | string) =>
      new Date(date).toLocaleDateString(locale, {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      });

    // --- Header ---
    let headerY = 50;
    if (institution.logo_url) {
      try {
        const logoPath = path.resolve(this.uploadDir, institution.logo_url);
        const resolvedUploadDir = path.resolve(this.uploadDir);
        if (
          logoPath.startsWith(resolvedUploadDir + path.sep) &&
          fs.existsSync(logoPath)
        ) {
          doc.image(logoPath, 50, headerY, { width: 50 });
        }
      } catch {
        // Skip logo on error
      }
    }

    const textX = institution.logo_url ? 110 : 50;
    doc.fontSize(16).font('Helvetica-Bold').text(institution.name, textX, headerY);
    doc.fontSize(9).font('Helvetica');
    if (institution.address) doc.text(institution.address, textX);
    const contactParts = [institution.phone, institution.email].filter(Boolean);
    if (contactParts.length) doc.text(contactParts.join(' | '), textX);

    doc.moveDown(2);

    // Separator
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e4e4e7');
    doc.moveDown();

    // --- Slip title ---
    doc.fontSize(20).font('Helvetica-Bold').text(labels.payoutSlip, { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica');
    doc.text(`${labels.slipNumber}: ${slipNumber}`, { align: 'center' });
    doc.text(`${labels.date}: ${formatDate(new Date())}`, { align: 'center' });
    doc.moveDown();

    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e4e4e7');
    doc.moveDown();

    // --- Pay To ---
    const tutorName = payout.tutor?.user?.name ?? payout.tutor?.name ?? '-';
    const bankInfo = [payout.tutor?.bank_name, payout.tutor?.bank_account_number]
      .filter(Boolean)
      .join(' - ');

    doc.fontSize(11).font('Helvetica-Bold').text(labels.payTo);
    doc.fontSize(10).font('Helvetica');
    doc.text(`${labels.tutor}: ${tutorName}`);
    if (bankInfo) doc.text(`${labels.bankAccount}: ${bankInfo}`);

    if (payout.period_start && payout.period_end) {
      doc.text(
        `${labels.period}: ${formatDate(payout.period_start)} — ${formatDate(payout.period_end)}`,
      );
    }
    doc.moveDown();

    // --- Session breakdown table ---
    if (sessions.length > 0) {
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e4e4e7');
      doc.moveDown();

      doc.font('Helvetica-Bold').fontSize(11).text(labels.sessionBreakdown);
      doc.moveDown(0.5);

      const tableY = doc.y;
      doc.font('Helvetica-Bold').fontSize(9);
      doc.text(labels.sessionDate, 50, tableY, { width: 120 });
      doc.text(labels.className, 170, tableY, { width: 220 });
      doc.text(labels.fee, 390, tableY, { align: 'right', width: 155 });

      doc.moveTo(50, tableY + 16).lineTo(545, tableY + 16).stroke('#e4e4e7');

      doc.font('Helvetica').fontSize(9);
      let rowY = tableY + 24;
      for (const session of sessions) {
        doc.text(formatDate(session.date), 50, rowY, { width: 120 });
        doc.text(session.class?.name ?? '-', 170, rowY, { width: 220 });
        doc.text(formatAmount(Number(session.tutor_fee_amount ?? 0)), 390, rowY, {
          align: 'right',
          width: 155,
        });
        rowY += 18;
      }

      doc.y = rowY;
      doc.moveDown();
    }

    // --- Net payout ---
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e4e4e7');
    doc.moveDown();

    doc.font('Helvetica-Bold').fontSize(11);
    doc.text(labels.netPayout, 300, doc.y);
    doc.text(
      formatAmount(Number(payout.amount)),
      300,
      doc.y - doc.currentLineHeight(),
      { align: 'right', width: 245 },
    );
    doc.font('Helvetica').fontSize(10);
    doc.moveDown();

    // Status
    const statusMap: Record<string, string> = {
      PENDING: labels.statusPending,
      PROCESSING: labels.statusProcessing,
      PAID: labels.statusPaid,
    };
    doc.text(`${labels.status}: ${statusMap[payout.status] ?? payout.status}`);
    doc.moveDown();

    // --- Footer ---
    doc.moveTo(50, doc.y + 10).lineTo(545, doc.y + 10).stroke('#e4e4e7');
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#a1a1aa').text(labels.footer, { align: 'center' });

    doc.end();
    return new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));
  }

  private flattenPayoutTutor(payout: any) {
    if (!payout.tutor) return payout;
    const { user, ...tutorRest } = payout.tutor;
    return {
      ...payout,
      tutor: {
        id: tutorRest.id,
        name: user?.name ?? '',
        bank_name: tutorRest.bank_name,
        bank_account_number: tutorRest.bank_account_number,
      },
    };
  }
}
